# Generated by Django 4.0.6 on 2022-07-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CPULoad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averageload',
            old_name='average_cpu_load',
            new_name='cpu_load',
        ),
        migrations.RenameField(
            model_name='instantload',
            old_name='instant_cpu_load',
            new_name='cpu_load',
        ),
    ]
